### ISSUE TITLE
Can't import Jquery?

### ISSUE THREAD

**Issue by quangtrang1111** [astoilkov/jsblocks#146]
I run app by run:
```
node app.js
```

Then I import jquery to index.html:
```
<script src="/bower_components/jquery/dist/jquery.js"></script>
```

And I got this error on browser:
```
TypeError: Cannot read property 'createElement' of undefined
   at assert (eval at <anonymous> (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11791:23), <anonymous>:15632:20)
   at eval (eval at <anonymous> (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11791:23), <anonymous>:17354:24)
   at eval (eval at <anonymous> (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11791:23), <anonymous>:17405:3)
   at arr (eval at <anonymous> (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11791:23), <anonymous>:14760:3)
   at eval (eval at <anonymous> (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11791:23), <anonymous>:14764:2)
   at C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11794:19
   at contextBubble (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11811:5)
   at executeCode (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11784:5)
   at executePageScripts (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:11779:5)
   at Object.Middleware._renderContents (C:\Users\quang\Desktop\jsblocks-shopping-example\node_modules\blocks\node\blocks-node.js:12254:9)
```

But it work if I run use:
```
blocks static
```

**Comment by Kanaye** [comment]
Hey @quangtrang1111,

jQuery assumes it's running in a browser and tries to  manipulate the (non-existent) dom.
You have to exclude jquery with ``data-client-only="true"`` on the including script tag.

Happy coding :smile:

**Comment by quangtrang1111** [comment]
@Kanaye thank you :+1: 
We should add this note to document.
