### ISSUE TITLE
SSR for building API used internal Expressjs.

### ISSUE THREAD

**Issue by Nipol** [astoilkov/jsblocks#67]
``` javascript
var blocks = require('blocks');
var server = blocks.server();
var app = server.express();

app.use(function(req, res, next) {
    console.log(req.method, req.get('content-type'), req.url);
    next(); 
});

app.get('/user/:id', function (req, res, next) {
  console.log(req.params.id);
  res.json({hello:'world'});
});
```

I wrote a app.js for SSR. with api.
so i requested to api

'/user/asdf'

I should have been. The json {hello:'world'}

but I had a different blink Page.
I confirm, it had to send the index.html.
and terminal log

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:334:11)
    at ServerResponse.header (Documents/jsblocks-seed/node_modules/blocks/node_modules/express/lib/response.js:666:10)
    at ServerResponse.send (Documents/jsblocks-seed/node_modules/blocks/node_modules/express/lib/response.js:146:12)
    at Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:12111:15
    at Object.Middleware._pageExecuted (Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:12162:7)
    at Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:11746:9
    at Object.ServerEnv.await (Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:11826:9)
    at handleResult (Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:11740:12)
    at Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:11696:9
    at Object.ServerEnv.await (Documents/jsblocks-seed/node_modules/blocks/node/blocks-node.js:11826:9)
```

And I thought, if the document is for data communication of the SSR wished.

And I have another opinion.
provide a 'fetch api' in jsblocks?
It seems to be able to provide a more isomorphic api.
just opinion.

**Comment by astoilkov** [comment]
I believe this is a bug. I am currently on a vacation. When I am back I will investigate this. Sorry for the late response.

**Comment by Kanaye** [comment]
Hi @Nipol.
Sorry for leaving this open for so long.
I didn't realize how easy this is "fixable".
Just for the case that this is still interesting for you.
your example from above will work in the next release with one modification,
you will need the following line after you added all your middlewares/routes:
``server.start();``
In case someone is not calling ``server.express()`` synchronously nothing changes so we stay compatible.

Regarding your fetch idea: I have something that-ish in mind and on my personal 'to think about'-list
but I think this is something for a sepperat issue that I'll open when I have a better idea  how that api will look.

Again sorry for leaving this issue.

have a nice day and greetings from germany
